/**
 * Unit tests for C++ renderer code generator
 *
 * Tests the generateCppRenderer function and component code generation.
 */

import { describe, test, expect } from "bun:test";
import { generateCppRenderer } from "../cpp";
import type { Project, Theme } from "@esphome-designer/schema";

const defaultTheme: Theme = {
  id: "retro",
  name: "Retro",
  colors: {
    background: { r: 0, g: 0, b: 0 },
    backgroundSecondary: { r: 30, g: 30, b: 30 },
    foreground: { r: 255, g: 255, b: 255 },
    foregroundMuted: { r: 128, g: 128, b: 128 },
    accent: { r: 255, g: 107, b: 0 },
  },
  style: {
    buttonShadow: true,
    containerCorners: true,
  },
  values: {
    cornerSize: 10,
    shadowOffset: 3,
  },
};

describe("C++ Renderer Generator", () => {
  describe("generateCppRenderer", () => {
    test("generates valid C++ header with pragma once", () => {
      const project: Project = {
        name: "Test Project",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        theme: defaultTheme,
        dashboardPages: [],
        detailViews: [],
      };

      const cpp = generateCppRenderer(project);

      expect(cpp).toContain("#pragma once");
      expect(cpp).toContain('#include "esphome.h"');
    });

    test("includes project info in header comment", () => {
      const project: Project = {
        name: "Home Display",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        theme: defaultTheme,
        dashboardPages: [],
        detailViews: [],
      };

      const cpp = generateCppRenderer(project);

      expect(cpp).toContain("AUTO-GENERATED by ESPHome Designer");
      expect(cpp).toContain("Project: Home Display");
      expect(cpp).toContain("Generated:");
    });

    test("includes required header dependencies", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        theme: defaultTheme,
        dashboardPages: [],
        detailViews: [],
      };

      const cpp = generateCppRenderer(project);

      expect(cpp).toContain('#include "state_manager.h"');
      expect(cpp).toContain('#include "render_helpers.h"');
      expect(cpp).toContain('#include "render_pages.h"');
      expect(cpp).toContain('#include "render_details.h"');
    });

    test("generates forward declarations for dashboard pages", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        theme: defaultTheme,
        dashboardPages: [
          { id: "page-0", name: "Home", components: [] },
          { id: "page-1", name: "Music", components: [] },
        ],
        detailViews: [],
      };

      const cpp = generateCppRenderer(project);

      expect(cpp).toContain("void renderPage0(display::Display& it);");
      expect(cpp).toContain("void renderPage1(display::Display& it);");
    });

    test("generates forward declarations for detail views", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        theme: defaultTheme,
        dashboardPages: [],
        detailViews: [
          { id: "TEMPS", title: "Temperatures", height: 400, components: [] },
          { id: "VACUUM", title: "Robot Vacuum", height: 500, components: [] },
        ],
      };

      const cpp = generateCppRenderer(project);

      expect(cpp).toContain("void renderDetail_TEMPS(display::Display& it);");
      expect(cpp).toContain("void renderDetail_VACUUM(display::Display& it);");
    });

    test("generates main renderDisplay dispatcher function", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        theme: defaultTheme,
        dashboardPages: [{ id: "page-0", name: "Home", components: [] }],
        detailViews: [],
      };

      const cpp = generateCppRenderer(project);

      expect(cpp).toContain("void renderDisplay(display::Display& it) {");
      expect(cpp).toContain("it.fill(Theme::BACKGROUND);");
    });

    test("generates dashboard page switch statement", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        theme: defaultTheme,
        dashboardPages: [
          { id: "page-0", name: "Home", components: [] },
          { id: "page-1", name: "Music", components: [] },
          { id: "page-2", name: "Climate", components: [] },
        ],
        detailViews: [],
      };

      const cpp = generateCppRenderer(project);

      expect(cpp).toContain("switch (gState.mainPageIndex) {");
      expect(cpp).toContain("case 0: renderPage0(it); break;");
      expect(cpp).toContain("case 1: renderPage1(it); break;");
      expect(cpp).toContain("case 2: renderPage2(it); break;");
    });

    test("generates detail view switch statement", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        theme: defaultTheme,
        dashboardPages: [],
        detailViews: [
          { id: "TEMPS", title: "Temps", height: 400, components: [] },
          { id: "LIGHTS", title: "Lights", height: 500, components: [] },
        ],
      };

      const cpp = generateCppRenderer(project);

      expect(cpp).toContain("switch (gState.currentView) {");
      expect(cpp).toContain(
        "case VIEW_DETAIL_TEMPS: renderDetail_TEMPS(it); break;"
      );
      expect(cpp).toContain(
        "case VIEW_DETAIL_LIGHTS: renderDetail_LIGHTS(it); break;"
      );
    });

    test("includes dashboard/detail view conditional", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        theme: defaultTheme,
        dashboardPages: [{ id: "page-0", name: "Home", components: [] }],
        detailViews: [
          { id: "TEMPS", title: "Temps", height: 400, components: [] },
        ],
      };

      const cpp = generateCppRenderer(project);

      expect(cpp).toContain("if (gState.currentView == VIEW_MAIN_DASHBOARD) {");
      expect(cpp).toContain("drawCommonHeader(it);");
      expect(cpp).toContain("} else {");
      expect(cpp).toContain("// Render detail view");
    });

    test("generates page indicator call with correct page count", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        theme: defaultTheme,
        dashboardPages: [
          { id: "page-0", name: "Home", components: [] },
          { id: "page-1", name: "Music", components: [] },
          { id: "page-2", name: "Climate", components: [] },
          { id: "page-3", name: "Lights", components: [] },
        ],
        detailViews: [],
      };

      const cpp = generateCppRenderer(project);

      expect(cpp).toContain("drawPageIndicator(it, gState.mainPageIndex, 4);");
    });

    test("handles empty project with no pages or views", () => {
      const project: Project = {
        name: "Empty Project",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        theme: defaultTheme,
        dashboardPages: [],
        detailViews: [],
      };

      const cpp = generateCppRenderer(project);

      expect(cpp).toContain("void renderDisplay(display::Display& it)");
      expect(cpp).toContain("drawPageIndicator(it, gState.mainPageIndex, 0);");
    });

    test("handles detail view IDs with hyphens", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        theme: defaultTheme,
        dashboardPages: [],
        detailViews: [
          {
            id: "LIVING-ROOM",
            title: "Living Room",
            height: 400,
            components: [],
          },
        ],
      };

      const cpp = generateCppRenderer(project);

      expect(cpp).toContain("void renderDetail_LIVING_ROOM(display::Display& it);");
      expect(cpp).toContain("case VIEW_DETAIL_LIVING_ROOM:");
    });
  });

  describe("Code Generation Quality", () => {
    test("generates syntactically correct C++ (no dangling braces)", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        theme: defaultTheme,
        dashboardPages: [
          { id: "page-0", name: "Home", components: [] },
          { id: "page-1", name: "Music", components: [] },
        ],
        detailViews: [
          { id: "TEMPS", title: "Temps", height: 400, components: [] },
        ],
      };

      const cpp = generateCppRenderer(project);

      // Count braces - should be balanced
      const openBraces = (cpp.match(/{/g) || []).length;
      const closeBraces = (cpp.match(/}/g) || []).length;
      expect(openBraces).toBe(closeBraces);
    });

    test("no duplicate forward declarations", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        theme: defaultTheme,
        dashboardPages: [
          { id: "page-0", name: "Home", components: [] },
          { id: "page-1", name: "Music", components: [] },
        ],
        detailViews: [],
      };

      const cpp = generateCppRenderer(project);

      const renderPage0Matches = cpp.match(
        /void renderPage0\(display::Display& it\);/g
      );
      expect(renderPage0Matches?.length).toBe(1);
    });

    test("includes default case in detail view switch", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        theme: defaultTheme,
        dashboardPages: [],
        detailViews: [
          { id: "TEMPS", title: "Temps", height: 400, components: [] },
        ],
      };

      const cpp = generateCppRenderer(project);

      expect(cpp).toContain("default: break;");
    });
  });
});
