/**
 * Unit tests for ESPHome YAML generator
 *
 * Tests the generateESPHomeYAML function and helper utilities.
 */

import { describe, test, expect } from "bun:test";
import { generateESPHomeYAML, entityToId } from "../esphome";
import type { Project } from "@esphome-designer/schema";

describe("ESPHome YAML Generator", () => {
  describe("generateESPHomeYAML", () => {
    test("generates valid YAML header with project info", () => {
      const project: Project = {
        name: "Test Display",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
      };

      const yaml = generateESPHomeYAML(project);

      expect(yaml).toContain("# Generated by ESPHome Designer");
      expect(yaml).toContain("# Project: Test Display");
      expect(yaml).toContain("Generated:");
    });

    test("generates device name from project name", () => {
      const project: Project = {
        name: "My Home Display",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
      };

      const yaml = generateESPHomeYAML(project);

      expect(yaml).toContain("device_name: my-home-display");
    });

    test("includes required ESPHome packages", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
      };

      const yaml = generateESPHomeYAML(project);

      expect(yaml).toContain("packages:");
      expect(yaml).toContain("sensors: !include sensors.yaml");
    });

    test("includes all required C++ header includes", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
      };

      const yaml = generateESPHomeYAML(project);

      expect(yaml).toContain("includes:");
      expect(yaml).toContain("- includes/display_renderer.h");
      expect(yaml).toContain("- includes/state_manager.h");
      expect(yaml).toContain("- includes/render_helpers.h");
      expect(yaml).toContain("- includes/render_pages.h");
      expect(yaml).toContain("- includes/render_details.h");
      expect(yaml).toContain("- includes/touch_handler.h");
    });

    test("generates correct display configuration", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "st7789" },
        dashboardPages: [],
        detailViews: [],
      };

      const yaml = generateESPHomeYAML(project);

      expect(yaml).toContain("display:");
      expect(yaml).toContain("platform: st7789");
      expect(yaml).toContain("width: 240");
      expect(yaml).toContain("height: 320");
    });

    test("generates display lambda with renderDisplay call", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
      };

      const yaml = generateESPHomeYAML(project);

      expect(yaml).toContain("lambda: |-");
      expect(yaml).toContain("renderDisplay(it);");
    });

    test("includes standard fonts configuration", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
      };

      const yaml = generateESPHomeYAML(project);

      expect(yaml).toContain("font:");
      expect(yaml).toContain('file: "gfonts://Share Tech Mono"');
      expect(yaml).toContain("id: font_small");
      expect(yaml).toContain("id: font_medium");
      expect(yaml).toContain("id: font_large");
    });

    test("includes globals for navigation state", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
      };

      const yaml = generateESPHomeYAML(project);

      expect(yaml).toContain("globals:");
      expect(yaml).toContain("id: current_page");
      expect(yaml).toContain("id: scroll_y");
      expect(yaml).toContain("id: max_scroll_y");
    });

    test("includes WiFi configuration with fallback AP", () => {
      const project: Project = {
        name: "Test Display",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
      };

      const yaml = generateESPHomeYAML(project);

      expect(yaml).toContain("wifi:");
      expect(yaml).toContain('ssid: "!secret wifi_ssid"');
      expect(yaml).toContain("ap:");
      expect(yaml).toContain('ssid: "${device_name} Fallback"');
    });

    test("includes I2C configuration for touchscreen", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
      };

      const yaml = generateESPHomeYAML(project);

      expect(yaml).toContain("i2c:");
      expect(yaml).toContain("id: i2c_touch");
      expect(yaml).toContain("sda: GPIO48");
      expect(yaml).toContain("scl: GPIO47");
    });

    test("includes SPI configuration for display", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
      };

      const yaml = generateESPHomeYAML(project);

      expect(yaml).toContain("spi:");
      expect(yaml).toContain("id: spi_lcd");
      expect(yaml).toContain("clk_pin: GPIO40");
      expect(yaml).toContain("mosi_pin: GPIO45");
    });

    test("includes display refresh interval", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
      };

      const yaml = generateESPHomeYAML(project);

      expect(yaml).toContain("interval:");
      expect(yaml).toContain("interval: 16ms");
      expect(yaml).toContain("id(main_display).update();");
    });

    test("lists dashboard pages in comments", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [
          { id: "page-0", name: "Home", components: [] },
          { id: "page-1", name: "Music", components: [] },
          { id: "page-2", name: "Climate", components: [] },
        ],
        detailViews: [],
      };

      const yaml = generateESPHomeYAML(project);

      expect(yaml).toContain("# Total dashboard pages: 3");
      expect(yaml).toContain("# Page 0: Home");
      expect(yaml).toContain("# Page 1: Music");
      expect(yaml).toContain("# Page 2: Climate");
    });

    test("includes API and OTA configuration", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
      };

      const yaml = generateESPHomeYAML(project);

      expect(yaml).toContain("api:");
      expect(yaml).toContain("reboot_timeout: 15min");
      expect(yaml).toContain("ota:");
      expect(yaml).toContain("platform: esphome");
    });

    test("includes time configuration for SNTP", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
      };

      const yaml = generateESPHomeYAML(project);

      expect(yaml).toContain("time:");
      expect(yaml).toContain("platform: sntp");
      expect(yaml).toContain("id: sntp_time");
    });

    test("includes Bluetooth proxy configuration", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
      };

      const yaml = generateESPHomeYAML(project);

      expect(yaml).toContain("esp32_ble_tracker:");
      expect(yaml).toContain("bluetooth_proxy:");
      expect(yaml).toContain("active: true");
    });

    test("handles project name with special characters", () => {
      const project: Project = {
        name: "Living Room  Display  v2",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
      };

      const yaml = generateESPHomeYAML(project);

      // Multiple spaces collapse to single hyphen
      expect(yaml).toContain("device_name: living-room-display-v2");
    });
  });

  describe("entityToId", () => {
    test("converts entity ID to valid C++ identifier", () => {
      expect(entityToId("sensor.outside_temperature")).toBe(
        "ha_sensor_outside_temperature"
      );
    });

    test("handles nested domain entities", () => {
      expect(entityToId("light.living_room")).toBe("ha_light_living_room");
    });

    test("handles binary sensors", () => {
      expect(entityToId("binary_sensor.motion")).toBe("ha_binary_sensor_motion");
    });

    test("handles climate entities", () => {
      expect(entityToId("climate.hvac")).toBe("ha_climate_hvac");
    });
  });
});
