/**
 * Unit tests for sensors YAML generator
 *
 * Tests the generateSensorsYAML function which creates ESPHome sensor
 * configurations for Home Assistant entity bindings.
 */

import { describe, test, expect } from "bun:test";
import { generateSensorsYAML } from "../sensors";
import type { Project, StateField } from "@esphome-designer/schema";

describe("Sensors YAML Generator", () => {
  describe("generateSensorsYAML", () => {
    test("generates valid YAML header with project info", () => {
      const project: Project = {
        name: "Test Display",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
      };

      const yaml = generateSensorsYAML(project);

      expect(yaml).toContain("# AUTO-GENERATED by ESPHome Designer");
      expect(yaml).toContain("# Project: Test Display");
      expect(yaml).toContain("# Generated:");
      expect(yaml).toContain("# DO NOT EDIT - regenerate from editor");
    });

    test("includes touchscreen template sensors", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
      };

      const yaml = generateSensorsYAML(project);

      expect(yaml).toContain("# Touchscreen coordinates");
      expect(yaml).toContain("sensor:");
      expect(yaml).toContain("platform: template");
      expect(yaml).toContain("id: touch_x_raw");
      expect(yaml).toContain("id: touch_y_raw");
      expect(yaml).toContain("id: touch_status");
    });

    test("marks touchscreen sensors as internal", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
      };

      const yaml = generateSensorsYAML(project);

      // Check that internal: true appears after each touch sensor
      expect(yaml).toMatch(/id: touch_x_raw\s+internal: true/);
      expect(yaml).toMatch(/id: touch_y_raw\s+internal: true/);
      expect(yaml).toMatch(/id: touch_status\s+internal: true/);
    });

    test("includes touch detection binary sensor", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
      };

      const yaml = generateSensorsYAML(project);

      expect(yaml).toContain("binary_sensor:");
      expect(yaml).toContain("id: touch_detected");
      expect(yaml).toContain("lambda: 'return false;'");
    });
  });

  describe("Numeric Sensors", () => {
    test("generates Home Assistant sensor for float fields", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
        state: {
          fields: [
            {
              name: "outsideTemp",
              cppType: "float",
              haEntity: "sensor.outside_temperature",
              defaultValue: 0,
            },
          ],
        },
      };

      const yaml = generateSensorsYAML(project);

      expect(yaml).toContain("platform: homeassistant");
      expect(yaml).toContain("id: ha_sensor_outsideTemp");
      expect(yaml).toContain("entity_id: sensor.outside_temperature");
      expect(yaml).toContain("internal: true");
    });

    test("generates Home Assistant sensor for int fields", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
        state: {
          fields: [
            {
              name: "humidity",
              cppType: "int",
              haEntity: "sensor.humidity",
              defaultValue: 50,
            },
          ],
        },
      };

      const yaml = generateSensorsYAML(project);

      expect(yaml).toContain("id: ha_sensor_humidity");
      expect(yaml).toContain("entity_id: sensor.humidity");
    });

    test("generates Home Assistant sensor for bool fields", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
        state: {
          fields: [
            {
              name: "isRaining",
              cppType: "bool",
              haEntity: "binary_sensor.rain",
              defaultValue: false,
            },
          ],
        },
      };

      const yaml = generateSensorsYAML(project);

      expect(yaml).toContain("id: ha_sensor_isRaining");
      expect(yaml).toContain("entity_id: binary_sensor.rain");
    });

    test("includes NaN filter for numeric sensors", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
        state: {
          fields: [
            {
              name: "temperature",
              cppType: "float",
              haEntity: "sensor.temperature",
            },
          ],
        },
      };

      const yaml = generateSensorsYAML(project);

      expect(yaml).toContain("filters:");
      expect(yaml).toContain('lambda: "return isnan(x) ? 0 : x;"');
    });

    test("updates gState on sensor value change", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
        state: {
          fields: [
            {
              name: "temperature",
              cppType: "float",
              haEntity: "sensor.temperature",
            },
          ],
        },
      };

      const yaml = generateSensorsYAML(project);

      expect(yaml).toContain("on_value:");
      expect(yaml).toContain('lambda: "gState.temperature = x;"');
    });

    test("generates multiple numeric sensors", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
        state: {
          fields: [
            {
              name: "tempIndoor",
              cppType: "float",
              haEntity: "sensor.indoor_temp",
            },
            {
              name: "tempOutdoor",
              cppType: "float",
              haEntity: "sensor.outdoor_temp",
            },
            {
              name: "humidity",
              cppType: "int",
              haEntity: "sensor.humidity",
            },
          ],
        },
      };

      const yaml = generateSensorsYAML(project);

      expect(yaml).toContain("id: ha_sensor_tempIndoor");
      expect(yaml).toContain("entity_id: sensor.indoor_temp");
      expect(yaml).toContain("id: ha_sensor_tempOutdoor");
      expect(yaml).toContain("entity_id: sensor.outdoor_temp");
      expect(yaml).toContain("id: ha_sensor_humidity");
      expect(yaml).toContain("entity_id: sensor.humidity");
    });
  });

  describe("Text Sensors", () => {
    test("generates text_sensor section for string fields", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
        state: {
          fields: [
            {
              name: "weatherCondition",
              cppType: "std::string",
              haEntity: "sensor.weather_condition",
              defaultValue: "unknown",
            },
          ],
        },
      };

      const yaml = generateSensorsYAML(project);

      expect(yaml).toContain("text_sensor:");
      expect(yaml).toContain("platform: homeassistant");
      expect(yaml).toContain("id: ha_text_weatherCondition");
      expect(yaml).toContain("entity_id: sensor.weather_condition");
      expect(yaml).toContain("internal: true");
    });

    test("updates gState on text sensor value change", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
        state: {
          fields: [
            {
              name: "status",
              cppType: "std::string",
              haEntity: "sensor.status",
            },
          ],
        },
      };

      const yaml = generateSensorsYAML(project);

      expect(yaml).toContain("on_value:");
      expect(yaml).toContain('lambda: "gState.status = x;"');
    });

    test("generates multiple text sensors", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
        state: {
          fields: [
            {
              name: "artistName",
              cppType: "std::string",
              haEntity: "media_player.spotify",
            },
            {
              name: "trackTitle",
              cppType: "std::string",
              haEntity: "media_player.spotify_title",
            },
          ],
        },
      };

      const yaml = generateSensorsYAML(project);

      expect(yaml).toContain("id: ha_text_artistName");
      expect(yaml).toContain("id: ha_text_trackTitle");
    });
  });

  describe("Mixed Sensor Types", () => {
    test("partitions fields into sensor and text_sensor sections", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
        state: {
          fields: [
            {
              name: "temperature",
              cppType: "float",
              haEntity: "sensor.temperature",
            },
            {
              name: "status",
              cppType: "std::string",
              haEntity: "sensor.status",
            },
            {
              name: "count",
              cppType: "int",
              haEntity: "sensor.count",
            },
            {
              name: "message",
              cppType: "std::string",
              haEntity: "sensor.message",
            },
          ],
        },
      };

      const yaml = generateSensorsYAML(project);

      // Numeric sensors should be under sensor:
      expect(yaml).toContain("id: ha_sensor_temperature");
      expect(yaml).toContain("id: ha_sensor_count");

      // String sensors should be under text_sensor:
      expect(yaml).toContain("text_sensor:");
      expect(yaml).toContain("id: ha_text_status");
      expect(yaml).toContain("id: ha_text_message");
    });

    test("text_sensor section appears after sensor section", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
        state: {
          fields: [
            {
              name: "temp",
              cppType: "float",
              haEntity: "sensor.temp",
            },
            {
              name: "status",
              cppType: "std::string",
              haEntity: "sensor.status",
            },
          ],
        },
      };

      const yaml = generateSensorsYAML(project);

      const sensorIndex = yaml.indexOf("ha_sensor_temp");
      const textSensorIndex = yaml.indexOf("text_sensor:");

      expect(sensorIndex).toBeLessThan(textSensorIndex);
    });
  });

  describe("Edge Cases", () => {
    test("handles empty state config", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
        state: {},
      };

      const yaml = generateSensorsYAML(project);

      // Should still have touchscreen sensors
      expect(yaml).toContain("id: touch_x_raw");
      // Should not have text_sensor section when no string fields
      expect(yaml).not.toMatch(/text_sensor:\s+- platform: homeassistant/);
    });

    test("handles undefined state config", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
      };

      const yaml = generateSensorsYAML(project);

      // Should still generate base sensors
      expect(yaml).toContain("sensor:");
      expect(yaml).toContain("id: touch_x_raw");
    });

    test("handles empty fields array", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
        state: {
          fields: [],
        },
      };

      const yaml = generateSensorsYAML(project);

      // Should still have touchscreen sensors
      expect(yaml).toContain("id: touch_x_raw");
      // No HA sensors should be generated
      expect(yaml).not.toContain("ha_sensor_");
      expect(yaml).not.toContain("ha_text_");
    });

    test("handles only string fields (no numeric)", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
        state: {
          fields: [
            {
              name: "status",
              cppType: "std::string",
              haEntity: "sensor.status",
            },
          ],
        },
      };

      const yaml = generateSensorsYAML(project);

      // Should have text_sensor section
      expect(yaml).toContain("text_sensor:");
      expect(yaml).toContain("id: ha_text_status");
      // Should not have any ha_sensor_ entries (only touch template sensors)
      expect(yaml).not.toContain("ha_sensor_");
    });

    test("handles only numeric fields (no strings)", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
        state: {
          fields: [
            {
              name: "temperature",
              cppType: "float",
              haEntity: "sensor.temperature",
            },
          ],
        },
      };

      const yaml = generateSensorsYAML(project);

      // Should have numeric sensor
      expect(yaml).toContain("id: ha_sensor_temperature");
      // Should not have text_sensor section with HA sensors
      expect(yaml).not.toContain("ha_text_");
    });
  });

  describe("YAML Format Quality", () => {
    test("generates proper YAML indentation", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
        state: {
          fields: [
            {
              name: "temp",
              cppType: "float",
              haEntity: "sensor.temp",
            },
          ],
        },
      };

      const yaml = generateSensorsYAML(project);

      // Check for proper 2-space indentation in sensor entries
      expect(yaml).toContain("  - platform: homeassistant");
      expect(yaml).toContain("    id:");
      expect(yaml).toContain("    entity_id:");
      expect(yaml).toContain("    internal:");
    });

    test("includes blank lines for readability", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
        state: {
          fields: [
            {
              name: "temp",
              cppType: "float",
              haEntity: "sensor.temp",
            },
            {
              name: "humidity",
              cppType: "float",
              haEntity: "sensor.humidity",
            },
          ],
        },
      };

      const yaml = generateSensorsYAML(project);

      // Should have blank lines between sensor definitions
      expect(yaml.split("\n\n").length).toBeGreaterThan(3);
    });
  });
});
