esphome:
  name: ${device_name}

esp32:
  variant: esp32s3
  framework:
    type: arduino
    sdkconfig_options:
      CONFIG_ESP_BROWNOUT_DET: "n"

logger:
  hardware_uart: USB_SERIAL_JTAG
  baud_rate: 115200
  level: DEBUG

wifi:
  ap:
    ssid: "${device_name} Fallback"
    password: "configme123"

captive_portal:

api:

ota:
  - platform: esphome
