/**
 * C++ Renderer Code Generator
 *
 * Generates C++ rendering code from the project schema.
 */

import type {
  Project,
  Page,
  Component,
  Color,
} from "@esphome-designer/schema";
import { entityToId } from "./esphome";

export function generateCppRenderer(project: Project): string {
  const lines: string[] = [];

  lines.push(`/**`);
  lines.push(` * AUTO-GENERATED by ESPHome Designer`);
  lines.push(` * Project: ${project.name}`);
  lines.push(` * Generated: ${new Date().toISOString()}`);
  lines.push(` */`);
  lines.push(``);
  lines.push(`#pragma once`);
  lines.push(`#include "esphome.h"`);
  lines.push(``);

  // Constants
  lines.push(`// Display dimensions`);
  lines.push(`const int DISPLAY_WIDTH = ${project.display.width};`);
  lines.push(`const int DISPLAY_HEIGHT = ${project.display.height};`);
  lines.push(``);

  // Color constants
  lines.push(`// Colors`);
  lines.push(`const Color C_BLACK(0, 0, 0);`);
  lines.push(`const Color C_WHITE(255, 255, 255);`);
  lines.push(`const Color C_ACCENT(74, 158, 255);`);
  lines.push(`const Color C_ORANGE(255, 107, 0);`);
  lines.push(``);

  // Forward declaration
  lines.push(`// Forward declarations`);
  lines.push(`extern esphome::globals::GlobalsComponent<int>* current_page;`);
  lines.push(``);

  // Generate page render functions
  for (let i = 0; i < project.pages.length; i++) {
    const page = project.pages[i];
    lines.push(generatePageRenderer(page, i, project));
    lines.push(``);
  }

  // Main render dispatcher
  lines.push(`// Main display render function`);
  lines.push(`void renderDisplay(display::Display& it, int page) {`);
  lines.push(`  // Clear display`);
  lines.push(`  it.fill(C_BLACK);`);
  lines.push(``);
  lines.push(`  // Render current page`);
  lines.push(`  switch (page) {`);
  for (let i = 0; i < project.pages.length; i++) {
    lines.push(`    case ${i}:`);
    lines.push(`      renderPage${i}(it);`);
    lines.push(`      break;`);
  }
  lines.push(`    default:`);
  lines.push(`      renderPage0(it);`);
  lines.push(`      break;`);
  lines.push(`  }`);
  lines.push(`}`);

  return lines.join("\n");
}

function generatePageRenderer(page: Page, index: number, project: Project): string {
  const lines: string[] = [];

  lines.push(`// Page ${index}: ${page.name}`);
  lines.push(`void renderPage${index}(display::Display& it) {`);

  // Background color
  if (page.backgroundColor) {
    lines.push(`  it.fill(${colorToCpp(page.backgroundColor)});`);
  }

  // Page title comment
  lines.push(`  // Page: ${page.name}`);
  lines.push(``);

  // Render each component
  for (const comp of page.components) {
    lines.push(generateComponentCode(comp, project));
  }

  lines.push(`}`);
  return lines.join("\n");
}

function generateComponentCode(comp: Component, project: Project): string {
  switch (comp.type) {
    case "text":
      return generateTextCode(comp);
    case "button":
      return generateButtonCode(comp);
    case "slider":
      return generateSliderCode(comp);
    case "gauge":
      return generateGaugeCode(comp);
    case "icon":
      return generateIconCode(comp);
    default:
      return `  // Unknown component type: ${(comp as Component).type}`;
  }
}

function generateTextCode(comp: Component & { type: "text" }): string {
  const x = comp.position.x;
  const y = comp.position.y;
  const color = comp.color ? colorToCpp(comp.color) : "C_WHITE";
  const font = comp.fontSize === "small" ? "font_small" : comp.fontSize === "large" ? "font_large" : "font_medium";
  const align = comp.align === "center" ? "TextAlign::CENTER" : comp.align === "right" ? "TextAlign::TOP_RIGHT" : "TextAlign::TOP_LEFT";

  const lines: string[] = [];
  lines.push(`  // Text: ${comp.id}`);

  if (comp.textBinding) {
    const sensorId = entityToId(comp.textBinding.entityId);
    lines.push(`  if (id(${sensorId}).has_state()) {`);
    lines.push(`    it.printf(${x}, ${y}, id(${font}), ${color}, ${align}, "%s", id(${sensorId}).state.c_str());`);
    lines.push(`  } else {`);
    lines.push(`    it.print(${x}, ${y}, id(${font}), ${color}, ${align}, "${comp.text ?? "---"}");`);
    lines.push(`  }`);
  } else {
    lines.push(`  it.print(${x}, ${y}, id(${font}), ${color}, ${align}, "${escapeString(comp.text ?? "")}");`);
  }

  return lines.join("\n");
}

function generateButtonCode(comp: Component & { type: "button" }): string {
  const x = comp.position.x;
  const y = comp.position.y;
  const w = comp.size?.width ?? 80;
  const h = comp.size?.height ?? 36;
  const bgColor = comp.backgroundColor ? colorToCpp(comp.backgroundColor) : "Color(50, 50, 50)";
  const label = escapeString(comp.label ?? "Button");

  const lines: string[] = [];
  lines.push(`  // Button: ${comp.id}`);
  lines.push(`  it.filled_rectangle(${x}, ${y}, ${w}, ${h}, ${bgColor});`);
  lines.push(`  it.rectangle(${x}, ${y}, ${w}, ${h}, Color(100, 100, 100));`);
  lines.push(`  it.printf(${x + w / 2}, ${y + h / 2}, id(font_medium), C_WHITE, TextAlign::CENTER, "${label}");`);

  return lines.join("\n");
}

function generateSliderCode(comp: Component & { type: "slider" }): string {
  const x = comp.position.x;
  const y = comp.position.y;
  const w = comp.size?.width ?? 120;
  const h = comp.size?.height ?? 24;
  const min = comp.min ?? 0;
  const max = comp.max ?? 100;
  const isVertical = comp.orientation === "vertical";

  const lines: string[] = [];
  lines.push(`  // Slider: ${comp.id}`);
  lines.push(`  {`);

  if (comp.valueBinding) {
    const sensorId = entityToId(comp.valueBinding.entityId);
    lines.push(`    float value = id(${sensorId}).has_state() ? id(${sensorId}).state : 0;`);
  } else {
    lines.push(`    float value = 50; // Mock value`);
  }

  lines.push(`    float normalized = (value - ${min}f) / (${max}f - ${min}f);`);
  lines.push(`    normalized = fmax(0.0f, fmin(1.0f, normalized));`);
  lines.push(``);
  lines.push(`    // Track`);
  lines.push(`    it.filled_rectangle(${x}, ${y}, ${w}, ${h}, Color(51, 51, 51));`);
  lines.push(``);

  if (isVertical) {
    lines.push(`    // Fill (vertical)`);
    lines.push(`    int fillH = (int)(${h} * normalized);`);
    lines.push(`    it.filled_rectangle(${x}, ${y + h} - fillH, ${w}, fillH, C_ACCENT);`);
  } else {
    lines.push(`    // Fill (horizontal)`);
    lines.push(`    int fillW = (int)(${w} * normalized);`);
    lines.push(`    it.filled_rectangle(${x}, ${y}, fillW, ${h}, C_ACCENT);`);
  }

  lines.push(`  }`);
  return lines.join("\n");
}

function generateGaugeCode(comp: Component & { type: "gauge" }): string {
  const w = comp.size?.width ?? 80;
  const h = comp.size?.height ?? 80;
  const cx = comp.position.x + w / 2;
  const cy = comp.position.y + h / 2;
  const radius = Math.min(w, h) / 2 - 5;
  const min = comp.min;
  const max = comp.max;
  const unit = escapeString(comp.unit ?? "");

  const lines: string[] = [];
  lines.push(`  // Gauge: ${comp.id}`);
  lines.push(`  {`);

  if (comp.valueBinding) {
    const sensorId = entityToId(comp.valueBinding.entityId);
    lines.push(`    float value = id(${sensorId}).has_state() ? id(${sensorId}).state : 0;`);
  } else {
    lines.push(`    float value = 65; // Mock value`);
  }

  lines.push(`    float normalized = (value - ${min}f) / (${max}f - ${min}f);`);
  lines.push(`    normalized = fmax(0.0f, fmin(1.0f, normalized));`);
  lines.push(`    float angle = -135.0f + (normalized * 270.0f);`);
  lines.push(`    float radians = angle * PI / 180.0f;`);
  lines.push(``);
  lines.push(`    // Background circle`);
  lines.push(`    it.filled_circle(${Math.round(cx)}, ${Math.round(cy)}, ${Math.round(radius)}, Color(42, 42, 42));`);
  lines.push(``);
  lines.push(`    // Needle`);
  lines.push(`    int needleLen = ${Math.round(radius - 15)};`);
  lines.push(`    int endX = ${Math.round(cx)} + (int)(needleLen * cos(radians));`);
  lines.push(`    int endY = ${Math.round(cy)} + (int)(needleLen * sin(radians));`);
  lines.push(`    it.line(${Math.round(cx)}, ${Math.round(cy)}, endX, endY, C_ORANGE);`);
  lines.push(``);
  lines.push(`    // Center dot`);
  lines.push(`    it.filled_circle(${Math.round(cx)}, ${Math.round(cy)}, 4, C_ORANGE);`);
  lines.push(``);
  lines.push(`    // Value text`);
  lines.push(`    char buf[16];`);
  lines.push(`    snprintf(buf, sizeof(buf), "%.0f${unit}", value);`);
  lines.push(`    it.printf(${Math.round(cx)}, ${Math.round(cy + radius / 2)}, id(font_medium), C_WHITE, TextAlign::CENTER, "%s", buf);`);
  lines.push(`  }`);

  return lines.join("\n");
}

function generateIconCode(comp: Component & { type: "icon" }): string {
  const x = comp.position.x;
  const y = comp.position.y;
  const color = comp.color ? colorToCpp(comp.color) : "C_WHITE";
  const iconName = escapeString(comp.icon);

  const lines: string[] = [];
  lines.push(`  // Icon: ${comp.id}`);
  lines.push(`  // Note: Icon rendering requires MDI font setup`);
  lines.push(`  // Icon: ${iconName} at (${x}, ${y})`);
  lines.push(`  it.printf(${x}, ${y}, id(font_medium), ${color}, TextAlign::CENTER, "?"); // Placeholder for icon`);

  return lines.join("\n");
}

function colorToCpp(color: Color): string {
  return `Color(${color.r}, ${color.g}, ${color.b})`;
}

function escapeString(str: string): string {
  return str
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t");
}
