import type { Project, StateField } from "@esphome-designer/schema";

export function generateSensorsYAML(project: Project): string {
  const fields = project.state?.fields ?? [];
  const sensors: StateField[] = [];
  const textSensors: StateField[] = [];

  // Partition by type
  for (const field of fields) {
    if (field.cppType === "std::string") {
      textSensors.push(field);
    } else {
      sensors.push(field);
    }
  }

  const lines: string[] = [];
  lines.push(`# AUTO-GENERATED by ESPHome Designer`);
  lines.push(`# Project: ${project.name}`);
  lines.push(`# Generated: ${new Date().toISOString()}`);
  lines.push(`# DO NOT EDIT - regenerate from editor`);
  lines.push(``);

  // Numeric sensors
  if (sensors.length > 0) {
    lines.push(`sensor:`);
    for (const field of sensors) {
      lines.push(`  - platform: homeassistant`);
      lines.push(`    id: ha_sensor_${field.name}`);
      lines.push(`    entity_id: ${field.haEntity}`);
      lines.push(`    internal: true`);
      lines.push(`    filters:`);
      lines.push(`      - lambda: "return isnan(x) ? 0 : x;"`);
      lines.push(`    on_value:`);
      lines.push(`      - lambda: "gState.${field.name} = x;"`);
      lines.push(``);
    }
  }

  // Text sensors
  if (textSensors.length > 0) {
    lines.push(`text_sensor:`);
    for (const field of textSensors) {
      lines.push(`  - platform: homeassistant`);
      lines.push(`    id: ha_text_${field.name}`);
      lines.push(`    entity_id: ${field.haEntity}`);
      lines.push(`    internal: true`);
      lines.push(`    on_value:`);
      lines.push(`      - lambda: "gState.${field.name} = x;"`);
      lines.push(``);
    }
  }

  return lines.join("\n");
}
