esphome:
  name: ${device_name}

esp32:
  variant: esp32s3
  framework:
    type: arduino
    sdkconfig_options:
      CONFIG_ESP_BROWNOUT_DET: "n"

logger:
  hardware_uart: USB_SERIAL_JTAG
  baud_rate: 115200

network:

wifi:
  output_power: 8.5dB
  ap:
    ssid: "${device_name} Fallback"
    password: "password"

captive_portal:

api:
  reboot_timeout: 15min

ota:
  - platform: esphome

time:
  - platform: sntp
    id: sntp_time
