font:
  - file: "gfonts://Orbitron"
    id: font_display
    size: 56
    glyphs: '0123456789°:.'
    ignore_missing_glyphs: true

  - file: "gfonts://Orbitron"
    id: font_medium
    size: 24
    glyphs: '!"%()+*-.,/:;° 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzÄÖÜäöüß'
    ignore_missing_glyphs: true

  - file: "gfonts://Orbitron"
    id: font_small
    size: 16
    glyphs: '!"%()+*-.,/:;° 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzÄÖÜäöüß'
    ignore_missing_glyphs: true
