version: "3.9"
services:
  app:
    build:
      dockerfile: packages/editor/Dockerfile
    ports:
      - "5173:5173"
    environment:
      - DATABASE_URL=postgresql://postgres:password@homelab:5432/esphome
      - NODE_ENV=development
      - CONCURRENT_JOBS=2